-- ============================================================================
-- Migration: Assign Buyer IDs and Seller IDs to Existing Users
-- Format: by0001, by0002, etc. for buyers
--         se0001, se0002, etc. for sellers
-- ============================================================================

-- Assign buyer_ids for all existing buyers
UPDATE users 
SET buyer_id = 'by' || LPAD(id::text, 4, '0')
WHERE role = 'BUYER' AND buyer_id IS NULL;

-- Assign seller_ids for all existing sellers
UPDATE users 
SET seller_id = 'se' || LPAD(id::text, 4, '0')
WHERE role = 'SELLER' AND seller_id IS NULL;

-- Verify the migration
-- SELECT id, name, email, role, buyer_id, seller_id FROM users;

-- Note: For NEW users created after this migration, buyer_id and seller_id 
-- will be automatically generated by the @PostPersist method in User.java

